name: buildx-publish

on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
          with:
            ref: master