name: buildx-publish

on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@master
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to docker
        env: # Or as an environment variable
          DOCKER_USERNAME: ${{ secrets.DockerUsername }}
          DOCKER_PASSWORD: ${{ secrets.DockerPassword }}
        run: echo $DOCKER_USERNAME | docker login -u $DOCKER_PASSWORD --password-stdin
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            . \
            -t fairbanksio/tiles-api:latest
            --push
      - uses: azure/container-actions/docker-login@master
        with:
          # login-server: contoso.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push Image
        run: |
          set -x
          docker push fairbanksio/tiles-api:latest