name: buildx-publish

on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v1
        with:
          ref: master
      -
        name: Set up BuildX
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@master
        with:
          version: latest
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            . \
            -t fairbanksio/tiles-api:latest
      - 
        name: Docker Login
        uses: azure/container-actions/docker-login@master
        with:
          # login-server: contoso.azurecr.io
          username: ${{ secrets.DockerUsername }}
          password: ${{ secrets.DockerPassword }}
      - 
        name: Push Image
        run: |
          set -x
          docker push fairbanksio/tiles-api:latest