name: buildx-publish

on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@master
        with:
          version: latest
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            . \
            -t fairbanksio/tiles-api:${{ github.sha }}
            --push
      - 
        name: Login and Publish to Docker
        uses: Azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.DockerUsername }}
          password: ${{ secrets.DockerPassword }}
        run: docker push fairbanksio/tiles-api:${{ github.sha }}