name: buildx-publish

on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@master
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      -
        name: Login to docker
        env: # Or as an environment variable
          DOCKER_USERNAME: 
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASS }}
        run: |
          echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            . \
            -t bsord/tiles-api:latest
            --push