name: buildx-publish

on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@master
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            -t fairbanksio/tiles-api:${{ github.sha }} \
            .
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DockerUsername }}
          password: ${{ secrets.DockerPassword }}
        run: |
          docker push fairbanksio/tiles-api:${{ github.sha }}